// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { Link, Text, useSitecore, RichText, Placeholder, NextImage, Image, CdpHelper, withDatasourceCheck, DateField } from '@sitecore-content-sdk/nextjs';
import { useState, useRef, useEffect } from 'react';
import React from 'react';
import { useI18n } from 'next-localization';
import { Facebook, Twitter, Youtube, Instagram, Linkedin, Share2, ArrowLeft, Phone, Plane, Bed, Camera, Navigation, X, Menu, Heart, Star, Calendar, Clock } from 'lucide-react';
import { LayoutStyles, PromoFlags } from '@/types/styleFlags';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/shadcn/components/ui/dropdown-menu';
import { EmailIcon, EmailShareButton, FacebookIcon, FacebookShareButton, LinkedinIcon, LinkedinShareButton, PinterestIcon, PinterestShareButton, TwitterIcon, TwitterShareButton } from 'react-share';
import Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 from 'next/link';
import { usePathname } from 'next/navigation';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/shadcn/components/ui/tabs';
import { useClickAway } from '@/hooks/useClickAway';
import { useStopResponsiveTransition } from '@/hooks/useStopResponsiveTransition';
import { extractMediaUrl } from '@/helpers/extractMediaUrl';
import { getLinkContent, getLinkField, isNavLevel, isNavRootItem, prepareFields } from '@/helpers/navHelpers';
import clsx from 'clsx';
import { isParamEnabled } from '@/helpers/isParamEnabled';
import { Drawer, DrawerTrigger, DrawerContent, DrawerClose } from '@/shadcn/components/ui/drawer';
import Head from 'next/head';
import SocialShare from 'src/components/non-sitecore/SocialShare';
import { DestinationHighlights } from 'src/components/non-sitecore/DestinationHighlights';
import { DestinationSidebar } from 'src/components/non-sitecore/DestinationSidebar';
import { ParentPathLink } from 'src/components/non-sitecore/ParentPathLink';
import { DestinationLinkedContent } from 'src/components/non-sitecore/DestinationLinkedContent';
import client from 'lib/sitecore-client';
import Image_5d8ce56058442d94361877e28c501c951a554a6a from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';
import { newsDateFormatter } from 'src/helpers/dateHelper';
import { Author } from 'src/components/non-sitecore/Author';

const importMap = [
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
      { name: 'useSitecore', value: useSitecore },
      { name: 'RichText', value: RichText },
      { name: 'Placeholder', value: Placeholder },
      { name: 'NextImage', value: NextImage },
      { name: 'Image', value: Image },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
      { name: 'DateField', value: DateField },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useState', value: useState },
      { name: 'useRef', value: useRef },
      { name: 'useEffect', value: useEffect },
      { name: 'default', value: React },
    ]
  },
  {
    module: 'next-localization',
    exports: [
      { name: 'useI18n', value: useI18n },
    ]
  },
  {
    module: 'lucide-react',
    exports: [
      { name: 'Facebook', value: Facebook },
      { name: 'Twitter', value: Twitter },
      { name: 'Youtube', value: Youtube },
      { name: 'Instagram', value: Instagram },
      { name: 'Linkedin', value: Linkedin },
      { name: 'Share2', value: Share2 },
      { name: 'ArrowLeft', value: ArrowLeft },
      { name: 'Phone', value: Phone },
      { name: 'Plane', value: Plane },
      { name: 'Bed', value: Bed },
      { name: 'Camera', value: Camera },
      { name: 'Navigation', value: Navigation },
      { name: 'X', value: X },
      { name: 'Menu', value: Menu },
      { name: 'Heart', value: Heart },
      { name: 'Star', value: Star },
      { name: 'Calendar', value: Calendar },
      { name: 'Clock', value: Clock },
    ]
  },
  {
    module: '@/types/styleFlags',
    exports: [
      { name: 'LayoutStyles', value: LayoutStyles },
      { name: 'PromoFlags', value: PromoFlags },
    ]
  },
  {
    module: '@/shadcn/components/ui/dropdown-menu',
    exports: [
      { name: 'DropdownMenu', value: DropdownMenu },
      { name: 'DropdownMenuContent', value: DropdownMenuContent },
      { name: 'DropdownMenuItem', value: DropdownMenuItem },
      { name: 'DropdownMenuTrigger', value: DropdownMenuTrigger },
    ]
  },
  {
    module: 'react-share',
    exports: [
      { name: 'EmailIcon', value: EmailIcon },
      { name: 'EmailShareButton', value: EmailShareButton },
      { name: 'FacebookIcon', value: FacebookIcon },
      { name: 'FacebookShareButton', value: FacebookShareButton },
      { name: 'LinkedinIcon', value: LinkedinIcon },
      { name: 'LinkedinShareButton', value: LinkedinShareButton },
      { name: 'PinterestIcon', value: PinterestIcon },
      { name: 'PinterestShareButton', value: PinterestShareButton },
      { name: 'TwitterIcon', value: TwitterIcon },
      { name: 'TwitterShareButton', value: TwitterShareButton },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 },
    ]
  },
  {
    module: 'next/navigation',
    exports: [
      { name: 'usePathname', value: usePathname },
    ]
  },
  {
    module: '@/shadcn/components/ui/tabs',
    exports: [
      { name: 'Tabs', value: Tabs },
      { name: 'TabsContent', value: TabsContent },
      { name: 'TabsList', value: TabsList },
      { name: 'TabsTrigger', value: TabsTrigger },
    ]
  },
  {
    module: '@/hooks/useClickAway',
    exports: [
      { name: 'useClickAway', value: useClickAway },
    ]
  },
  {
    module: '@/hooks/useStopResponsiveTransition',
    exports: [
      { name: 'useStopResponsiveTransition', value: useStopResponsiveTransition },
    ]
  },
  {
    module: '@/helpers/extractMediaUrl',
    exports: [
      { name: 'extractMediaUrl', value: extractMediaUrl },
    ]
  },
  {
    module: '@/helpers/navHelpers',
    exports: [
      { name: 'getLinkContent', value: getLinkContent },
      { name: 'getLinkField', value: getLinkField },
      { name: 'isNavLevel', value: isNavLevel },
      { name: 'isNavRootItem', value: isNavRootItem },
      { name: 'prepareFields', value: prepareFields },
    ]
  },
  {
    module: 'clsx',
    exports: [
      { name: 'default', value: clsx },
    ]
  },
  {
    module: '@/helpers/isParamEnabled',
    exports: [
      { name: 'isParamEnabled', value: isParamEnabled },
    ]
  },
  {
    module: '@/shadcn/components/ui/drawer',
    exports: [
      { name: 'Drawer', value: Drawer },
      { name: 'DrawerTrigger', value: DrawerTrigger },
      { name: 'DrawerContent', value: DrawerContent },
      { name: 'DrawerClose', value: DrawerClose },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'src/components/non-sitecore/SocialShare',
    exports: [
      { name: 'default', value: SocialShare },
    ]
  },
  {
    module: 'src/components/non-sitecore/DestinationHighlights',
    exports: [
      { name: 'DestinationHighlights', value: DestinationHighlights },
    ]
  },
  {
    module: 'src/components/non-sitecore/DestinationSidebar',
    exports: [
      { name: 'DestinationSidebar', value: DestinationSidebar },
    ]
  },
  {
    module: 'src/components/non-sitecore/ParentPathLink',
    exports: [
      { name: 'ParentPathLink', value: ParentPathLink },
    ]
  },
  {
    module: 'src/components/non-sitecore/DestinationLinkedContent',
    exports: [
      { name: 'DestinationLinkedContent', value: DestinationLinkedContent },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image_5d8ce56058442d94361877e28c501c951a554a6a },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  },
  {
    module: 'src/helpers/dateHelper',
    exports: [
      { name: 'newsDateFormatter', value: newsDateFormatter },
    ]
  },
  {
    module: 'src/components/non-sitecore/Author',
    exports: [
      { name: 'Author', value: Author },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
