// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { Link, Text, useSitecore, Placeholder, RichText, NextImage, Image, CdpHelper, withDatasourceCheck, DateField } from '@sitecore-content-sdk/nextjs';
import { useState, useRef, useEffect } from 'react';
import React from 'react';
import { Facebook, Twitter, Youtube, Instagram, Linkedin, ChevronDown, ArrowLeft, Calendar, Clock, Heart, Share2 } from 'lucide-react';
import { isParamEnabled } from '@/helpers/isParamEnabled';
import HamburgerIcon from '@/components/non-sitecore/HamburgerIcon';
import { useClickAway } from '@/hooks/useClickAway';
import { useStopResponsiveTransition } from '@/hooks/useStopResponsiveTransition';
import { extractMediaUrl } from '@/helpers/extractMediaUrl';
import { getLinkContent, getLinkField, isNavLevel, isNavRootItem, prepareFields } from '@/helpers/navHelpers';
import clsx from 'clsx';
import Head from 'next/head';
import client from 'lib/sitecore-client';
import Image_5d8ce56058442d94361877e28c501c951a554a6a from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';
import { newsDateFormatter } from 'src/helpers/dateHelper';
import { Author } from 'src/components/non-sitecore/Author';

const importMap = [
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
      { name: 'useSitecore', value: useSitecore },
      { name: 'Placeholder', value: Placeholder },
      { name: 'RichText', value: RichText },
      { name: 'NextImage', value: NextImage },
      { name: 'Image', value: Image },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
      { name: 'DateField', value: DateField },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useState', value: useState },
      { name: 'useRef', value: useRef },
      { name: 'useEffect', value: useEffect },
      { name: 'default', value: React },
    ]
  },
  {
    module: 'lucide-react',
    exports: [
      { name: 'Facebook', value: Facebook },
      { name: 'Twitter', value: Twitter },
      { name: 'Youtube', value: Youtube },
      { name: 'Instagram', value: Instagram },
      { name: 'Linkedin', value: Linkedin },
      { name: 'ChevronDown', value: ChevronDown },
      { name: 'ArrowLeft', value: ArrowLeft },
      { name: 'Calendar', value: Calendar },
      { name: 'Clock', value: Clock },
      { name: 'Heart', value: Heart },
      { name: 'Share2', value: Share2 },
    ]
  },
  {
    module: '@/helpers/isParamEnabled',
    exports: [
      { name: 'isParamEnabled', value: isParamEnabled },
    ]
  },
  {
    module: '@/components/non-sitecore/HamburgerIcon',
    exports: [
      { name: 'default', value: HamburgerIcon },
    ]
  },
  {
    module: '@/hooks/useClickAway',
    exports: [
      { name: 'useClickAway', value: useClickAway },
    ]
  },
  {
    module: '@/hooks/useStopResponsiveTransition',
    exports: [
      { name: 'useStopResponsiveTransition', value: useStopResponsiveTransition },
    ]
  },
  {
    module: '@/helpers/extractMediaUrl',
    exports: [
      { name: 'extractMediaUrl', value: extractMediaUrl },
    ]
  },
  {
    module: '@/helpers/navHelpers',
    exports: [
      { name: 'getLinkContent', value: getLinkContent },
      { name: 'getLinkField', value: getLinkField },
      { name: 'isNavLevel', value: isNavLevel },
      { name: 'isNavRootItem', value: isNavRootItem },
      { name: 'prepareFields', value: prepareFields },
    ]
  },
  {
    module: 'clsx',
    exports: [
      { name: 'default', value: clsx },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image_5d8ce56058442d94361877e28c501c951a554a6a },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  },
  {
    module: 'src/helpers/dateHelper',
    exports: [
      { name: 'newsDateFormatter', value: newsDateFormatter },
    ]
  },
  {
    module: 'src/components/non-sitecore/Author',
    exports: [
      { name: 'Author', value: Author },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
