// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import { combineImportEntries, defaultImportEntries } from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { Link, Text, useSitecore, Placeholder, RichText, NextImage, Image, CdpHelper, withDatasourceCheck } from '@sitecore-content-sdk/nextjs';
import { useEffect, useState, useRef, useMemo, useCallback } from 'react';
import React from 'react';
import { ChevronLeft, ChevronRight, User, Heart, ShoppingCart, X, ArrowLeft, Check, Globe, Menu } from 'lucide-react';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Autoplay, Navigation } from 'swiper/modules';
import { isParamEnabled } from '@/helpers/isParamEnabled';
import { useI18n } from 'next-localization';
import QuantityControl from 'src/components/non-sitecore/QuantityControl';
import { useLocale } from '@/hooks/useLocaleOptions';
import { useCartAction } from '@/hooks/useCartAction';
import { getCart } from '@/lib/cart';
import { DrawerClose, Drawer, DrawerContent, DrawerTrigger } from '@/shadcn/components/ui/drawer';
import { MiniCart } from 'src/components/non-sitecore/MiniCart';
import { useClickAway } from '@/hooks/useClickAway';
import { useStopResponsiveTransition } from '@/hooks/useStopResponsiveTransition';
import { extractMediaUrl } from '@/helpers/extractMediaUrl';
import { getLinkContent, getLinkField, isNavLevel, isNavRootItem, prepareFields } from '@/helpers/navHelpers';
import clsx from 'clsx';
import { useRouter } from 'next/router';
import { localeOptions } from '@/constants/localeOptions';
import Head from 'next/head';
import client from 'lib/sitecore-client';
import Image_5d8ce56058442d94361877e28c501c951a554a6a from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';

const importMap = [
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
      { name: 'useSitecore', value: useSitecore },
      { name: 'Placeholder', value: Placeholder },
      { name: 'RichText', value: RichText },
      { name: 'NextImage', value: NextImage },
      { name: 'Image', value: Image },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useEffect', value: useEffect },
      { name: 'useState', value: useState },
      { name: 'useRef', value: useRef },
      { name: 'useMemo', value: useMemo },
      { name: 'useCallback', value: useCallback },
      { name: 'default', value: React },
    ]
  },
  {
    module: 'lucide-react',
    exports: [
      { name: 'ChevronLeft', value: ChevronLeft },
      { name: 'ChevronRight', value: ChevronRight },
      { name: 'User', value: User },
      { name: 'Heart', value: Heart },
      { name: 'ShoppingCart', value: ShoppingCart },
      { name: 'X', value: X },
      { name: 'ArrowLeft', value: ArrowLeft },
      { name: 'Check', value: Check },
      { name: 'Globe', value: Globe },
      { name: 'Menu', value: Menu },
    ]
  },
  {
    module: 'swiper/react',
    exports: [
      { name: 'Swiper', value: Swiper },
      { name: 'SwiperSlide', value: SwiperSlide },
    ]
  },
  {
    module: 'swiper/modules',
    exports: [
      { name: 'Autoplay', value: Autoplay },
      { name: 'Navigation', value: Navigation },
    ]
  },
  {
    module: '@/helpers/isParamEnabled',
    exports: [
      { name: 'isParamEnabled', value: isParamEnabled },
    ]
  },
  {
    module: 'next-localization',
    exports: [
      { name: 'useI18n', value: useI18n },
    ]
  },
  {
    module: 'src/components/non-sitecore/QuantityControl',
    exports: [
      { name: 'default', value: QuantityControl },
    ]
  },
  {
    module: '@/hooks/useLocaleOptions',
    exports: [
      { name: 'useLocale', value: useLocale },
    ]
  },
  {
    module: '@/hooks/useCartAction',
    exports: [
      { name: 'useCartAction', value: useCartAction },
    ]
  },
  {
    module: '@/lib/cart',
    exports: [
      { name: 'getCart', value: getCart },
    ]
  },
  {
    module: '@/shadcn/components/ui/drawer',
    exports: [
      { name: 'DrawerClose', value: DrawerClose },
      { name: 'Drawer', value: Drawer },
      { name: 'DrawerContent', value: DrawerContent },
      { name: 'DrawerTrigger', value: DrawerTrigger },
    ]
  },
  {
    module: 'src/components/non-sitecore/MiniCart',
    exports: [
      { name: 'MiniCart', value: MiniCart },
    ]
  },
  {
    module: '@/hooks/useClickAway',
    exports: [
      { name: 'useClickAway', value: useClickAway },
    ]
  },
  {
    module: '@/hooks/useStopResponsiveTransition',
    exports: [
      { name: 'useStopResponsiveTransition', value: useStopResponsiveTransition },
    ]
  },
  {
    module: '@/helpers/extractMediaUrl',
    exports: [
      { name: 'extractMediaUrl', value: extractMediaUrl },
    ]
  },
  {
    module: '@/helpers/navHelpers',
    exports: [
      { name: 'getLinkContent', value: getLinkContent },
      { name: 'getLinkField', value: getLinkField },
      { name: 'isNavLevel', value: isNavLevel },
      { name: 'isNavRootItem', value: isNavRootItem },
      { name: 'prepareFields', value: prepareFields },
    ]
  },
  {
    module: 'clsx',
    exports: [
      { name: 'default', value: clsx },
    ]
  },
  {
    module: 'next/router',
    exports: [
      { name: 'useRouter', value: useRouter },
    ]
  },
  {
    module: '@/constants/localeOptions',
    exports: [
      { name: 'localeOptions', value: localeOptions },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image_5d8ce56058442d94361877e28c501c951a554a6a },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  }
];

export default combineImportEntries(defaultImportEntries, importMap);
